export default {
    sounds: {
        backpack: new AudioClip("sounds/backpack.mp3"),
        levelup: new AudioClip("sounds/levelup.mp3"),
        abouttodie: new AudioClip("sounds/abouttodie.mp3"),
        goblinHit: new AudioClip("sounds/goblin_hit.mp3"),
        punch: new AudioClip("sounds/punch.mp3"),
        playerHit: new AudioClip("sounds/player_hit.mp3"),
        playerHit2: new AudioClip("sounds/player_hit2.mp3"),
        peasantunlock: new AudioClip("sounds/peasantunlock.mp3"),
        fighterhit: new AudioClip("sounds/fighterhit.mp3"),
        evillaugh: new AudioClip("sounds/crazyChickLaugh.mp3"),
        killping: new AudioClip("sounds/killping.mp3"),
        orclaugh: new AudioClip("sounds/orclaugh.mp3"),
        deathzone: new AudioClip("sounds/deathzone.mp3"),
        orkish1: new AudioClip("sounds/sharath.mp3"),
        orkish2: new AudioClip("sounds/riseofempire.mp3"),
        orkish3: new AudioClip("sounds/redstorm.mp3"),
        orkish4: new AudioClip("sounds/ogre-dragons.mp3"),
        orkish5: new AudioClip("sounds/northwind.mp3"),
        orkish6: new AudioClip("sounds/kronn.mp3"),
        orkish7: new AudioClip("sounds/hammerhold.mp3"),
        orkish8: new AudioClip("sounds/gor.mp3"),
        orkish9: new AudioClip("sounds/dominionreforged.mp3"),
        orkish10: new AudioClip("sounds/blackmarch.mp3"),
        playerdeath: new AudioClip("sounds/playerdeath.mp3"),
        shopkeeper: new AudioClip("sounds/shopkeeper.mp3"),
        victory: new AudioClip("sounds/2015-08-18_-_Victory_-_David_Fesliyan.mp3"),
        sheathsword: new AudioClip("sounds/sheathsword.mp3"),
        corkpop: new AudioClip("sounds/corkpop.mp3"),
        wardspell: new AudioClip("sounds/279103-Magic-Game-Protection-Ward-Buff.wav"),
        elementalspell: new AudioClip("sounds/407875-Elemental_-Good_Cast_Single_Protection-5.wav")
    },
    animations: {
        riversWalkClip: new AnimationState("walking"),
        turnRClip: new AnimationState("rightTurn"),
        turnLClip: new AnimationState("turnLeft")
    },
    models: {
        bigrocks: new GLTFShape("models/bigrocks.glb"),
        smallrocks: new GLTFShape("models/smallrocks.glb"),
        birchtree: new GLTFShape("models/birchtree.glb"),
        pinetree: new GLTFShape("models/pinetree.glb"),
        box: new GLTFShape("models/box.glb"),
        staticobjects: new GLTFShape("models/static_objects_glb.glb"),
        animatedleaves: new GLTFShape("models/leaves_falling_glb.glb"),
        lantern: new GLTFShape("models/lantern_glb.glb"),
        pyramid_bottom: new GLTFShape("models/pyramid_bottom_section_glb.glb"),
        pyramid_top: new GLTFShape("models/pyramid_top_section_glb.glb"),
        pyramid_sand: new GLTFShape("models/pyramid_ground_section_glb.glb"),
        pyramid_rocks: new GLTFShape("models/pyramid_rocks_glb.glb"),
        flag1: new GLTFShape("models/small_flag01_glb.glb"),
        flag2: new GLTFShape("models/small_flag02_glb.glb"),
        flag3: new GLTFShape("models/big_flag_glb.glb"),
        grassblades: new GLTFShape("models/grass_glb.glb"),
        skullsandbones: new GLTFShape("models/skullsandbones.glb"),
        duatsky: new GLTFShape("models/duatsky.glb"),
        orcgrunt: new GLTFShape("models/orcgrunt6.glb"),
        orcpeon: new GLTFShape("models/peon3.glb"),
        orcwarrior: new GLTFShape("models/warrior.glb"),
        oldanpu: new GLTFShape("models/anpu.glb"),
        anpu: new GLTFShape("models/anubis1.glb"),
        peasant: new GLTFShape("models/peasant1.glb"),
        redpeasant: new GLTFShape("models/redpeasant.glb"),
        paladin: new GLTFShape("models/paladin8.glb"),
        orc_camp: new GLTFShape("models/orc_encampment_model.glb"),
        smoke1: new GLTFShape("models/smoke_animated_01.glb"),
        smoke2: new GLTFShape("models/smoke_animated_02.glb"),
        smokewavy: new GLTFShape("models/smoke_01_waving_glb.glb"),
        fist: new GLTFShape("models/fist_punching_glb.glb"),
        potionshop: new GLTFShape("models/shop_model_glb.glb"),
        shoplight: new GLTFShape("models/shop_light.glb.glb"),
        duatlight: new GLTFShape("models/lantern.glb"),
        duatwall: new GLTFShape("models/blackwall.glb"),
        shopsmoke1: new GLTFShape("models/shop_smoke01_glb.glb"),
        shopsmoke2: new GLTFShape("models/shop_smoke02_glb.glb"),
        anpuartifact: new GLTFShape("models/death/anpu_artifact_glb.glb"),
        bonemound: new GLTFShape("models/death/mounds_bones_glb.glb"),
        walldivider: new GLTFShape("models/death/wall_diviver_glb.glb"),
        pyramid: new GLTFShape("models/mediumpyramid.glb"),
        largepyramid: new GLTFShape("models/largepyramid.glb"),
        merchantshop: new GLTFShape("models/merchantbuilding.glb")
    },
    loot: {
        greekSword: new Texture("images/looticons/greeksword.png"),
        sandBeetle: new Texture("images/looticons/sandbeetle.png"),
        rustysword: new Texture("images/looticons/rustysword.png"),
        rustyaxe: new Texture("images/looticons/rustyaxe.png"),
        rustydagger: new Texture("images/looticons/rustydagger.png"),
        orctooth: new Texture("images/looticons/orctooth.png"),
        redPotion: new Texture("images/looticons/redHealthPotion.png"),
        bluePotion: new Texture("images/looticons/blueHealthPotion.png"),
        greenPotion: new Texture("images/looticons/greenHealthPotion.png"),
        mana: new Texture("images/looticons/mana.png")
    },
    spells: {
        shield: new Texture("images/spells/painterly-spell-icons-1/enchant-blue-1.png")
    },
    interface: {
        questLog: new Texture("images/vali/QuestLog.jpeg"),
        warriorScreen: new Texture("images/vali/WarriorCharacterScreen.png"),
        berzerkerScreen: new Texture("images/vali/BerzerkerCharacterScreen.png"),
        rogueScreen: new Texture("images/vali/RogueCharacterScreen.png"),
        characterScreen: new Texture("images/vali/CharacterScreen.png"),
        blueActionBar: new Texture("images/vali/BlueActionbar.png"),
        blueBackpack: new Texture("images/vali/BlueBackpack.png"),
        blueLootWindow: new Texture("images/vali/BlueLootwindow.png"),
        blueMerchantInterface: new Texture("images/vali/BlueMerchantInterface.png"),
        khepra: new Texture("images/khepra.png"),
        buybutton: new Texture("images/dialogs/buybutton.png"),
        connectbutton: new Texture("images/dialogs/metamask.png"),
        combatlog: new Texture("images/vali/CombatLog.png"),
        closebutton: new Texture("images/vali/CloseButton.png"),
        equipButton:     new Texture("images/equip_button.png"),
        characterButton: new Texture("images/character_button.png")
    }
}